import {API_URL,API_KEY,PUBLIC_URL,esc,clone,uid,TOKENS,SPARKLES,normalizeDocument,publicDocument,publishIssues,resolveText,copyText,storageGet,storageSet,downloadJSON} from '../core.mjs?v=20260923.1';
const $=id=>document.getElementById(id), db=globalThis.supabase?.createClient(API_URL,API_KEY);
let user=null,demo=false,doc=null,row=null,pub=null,dirty=false,busy=false,panel='',filter='',editId=null,undo=[],recovery=null,toastTimer,confirmResolve;
const key=()=>demo?'teiki:demo':'teiki:unsaved:'+user?.id;
function status(t,error=false){$('status').textContent=t;$('status').className=t?'message'+(error?' error':''):'';}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2500);}
function ask(title,text,button='実行する'){return new Promise(resolve=>{$('confirmTitle').textContent=title;$('confirmText').textContent=text;$('confirmYes').textContent=button;confirmResolve=resolve;$('confirmDialog').showModal();});}
function finishAsk(value){$('confirmDialog').close();const fn=confirmResolve;confirmResolve=null;fn?.(value);}
$('confirmYes').onclick=()=>finishAsk(true);$('confirmNo').onclick=()=>finishAsk(false);$('confirmDialog').addEventListener('cancel',()=>{const fn=confirmResolve;confirmResolve=null;fn?.(false);});
function remember(){const ok=recovery?true:storageSet(key(),{document:doc,revision:row?.revision||0,dirty,at:Date.now()});$('saveState').textContent=demo?'お試し編集中':dirty?(ok?'編集中・この端末に一時保存':'編集中・一時保存できません。下書き保存してください'):'下書き保存済み'+(pub?.is_published?' ／ 公開済み':' ／ 未公開');}
function changed(fn,render=true){if(busy)return;if(recovery)return toast('先に一時保存した編集を復元するか、保存済みを使うか選んでください。');undo.push(clone(doc));if(undo.length>15)undo.shift();fn();dirty=true;remember();if(render)renderPanel();}
function applyRow(data){row=data;doc=normalizeDocument(data.document);dirty=false;remember();}
async function starter(){const r=await fetch('../starter.json?v=20260923.1');if(!r.ok)throw Error('テンプレートを読み込めませんでした。');return normalizeDocument(await r.json());}
function showStudio(){ $('loginView').hidden=true;$('studio').hidden=false;$('logoutBtn').hidden=false;$('logoutBtn').textContent=demo?'ログインへ':'ログアウト';$('identity').textContent=demo?'お試し・公開されません':user.email;$('saveBtn').textContent=demo?'端末に保存':'下書き保存';dashboard();remember();}
function dashboard(){panel='';$('dashboard').hidden=false;$('panel').hidden=true;$('dashboardBtn').hidden=true;}
$('dashboardBtn').onclick=dashboard;
async function loadAccount(){
 const {data,error}=await db.from('teiki_drafts').select('*').eq('owner_user_id',user.id).maybeSingle();if(error)throw Error('保存データを読み込めませんでした。再読み込みしてください。');row=data;
 if(row){doc=normalizeDocument(row.document);const result=await db.from('teiki_publications').select('*').eq('page_id',row.id).maybeSingle();if(result.error)throw result.error;pub=result.data;}
 else{doc=await starter();doc.settings={...doc.settings,name:'',mark:'',goal:'',current:'',peopleGoal:'',peopleCurrent:''};doc.comments.forEach(c=>{if(/\{\{(目標|現在|残り)/.test(c.text))c.visible=false;});const p=await db.from('streamer_profiles').select('display_name,fan_mark').eq('owner_user_id',user.id).order('created_at').limit(1).maybeSingle();if(p.data){doc.settings.name=p.data.display_name;doc.settings.mark=p.data.fan_mark||'';}pub=null;}
 dirty=false;recovery=storageGet(key(),null);if(!recovery?.dirty||JSON.stringify(recovery.document)===JSON.stringify(doc))recovery=null;showStudio();
 if(recovery?.dirty&&JSON.stringify(recovery.document)!==JSON.stringify(doc)){$('recoveryNotice').hidden=false;if(recovery.revision!==(row?.revision||0)){$('recoveryNotice').firstChild.textContent='別端末で新しい内容が保存されています。この端末の編集はバックアップとして書き出せます。';$('recoverBtn').textContent='編集を書き出す';}}
 status('');
}
$('recoverBtn').onclick=()=>{if(!recovery)return;if(recovery.revision!==(row?.revision||0)){downloadJSON(recovery.document,'teiki_unsaved_backup.json');return;}try{doc=normalizeDocument(recovery.document);recovery=null;dirty=true;remember();$('recoveryNotice').hidden=true;renderPanel();toast('この端末の編集を復元しました');}catch(e){status(e.message,true);}};
$('discardRecovery').onclick=()=>{$('recoveryNotice').hidden=true;recovery=null;remember();};
async function persist(){if(busy)return false;if(recovery){toast('先に一時保存の内容を確認してください。');return false;}try{const valid=normalizeDocument(doc);if(demo){doc=valid;dirty=false;remember();toast('この端末に保存しました');return true;}busy=true;$('studio').inert=true;status('下書きを保存中…');const {data,error}=await db.rpc('teiki_save',{p_document:valid,p_expected_revision:row?.revision||0});if(error)throw error;applyRow(data);status('下書きを保存しました。公開ページは「公開する」で更新します。');return true;}catch(e){if((e.message||'').includes('TEIKI_CONFLICT'))status('別の画面で更新されています。共有・保存からバックアップを書き出し、再読み込みしてください。入力中の内容は残っています。',true);else status('保存できませんでした。入力は残っています。'+friendly(e),true);return false;}finally{busy=false;$('studio').inert=false;}}
function friendly(e){const m=e?.message||'';if(/JWT|token|session|auth/i.test(m))return 'ログインし直してください。';if(m.includes('TEIKI_INVALID'))return '入力内容と未入力の項目を確認してください。';return m.includes('Failed to fetch')?'通信状態を確認してください。':'';}
$('saveBtn').onclick=persist;
function inputField(id,label,value,{number=false,max=60,type='text'}={}){return `<div class="field"><label for="s_${id}">${label}</label><input id="s_${id}" data-setting="${id}" value="${esc(value)}" ${number?'inputmode="numeric" pattern="[0-9]*"':''} type="${type}" maxlength="${max}"></div>`;}
function renderPanel(){if(!panel)return;let html='';
 if(panel==='basics')html='<h2>基本情報</h2><div class="form-grid">'+inputField('name','配信者名',doc.settings.name)+inputField('mark','推しマ',doc.settings.mark,{max:40})+inputField('title','ページタイトル',doc.settings.title)+'<div class="field"><label for="s_accent">アクセントカラー</label><input class="settings-color" id="s_accent" data-setting="accent" type="color" value="'+esc(doc.settings.accent)+'"></div></div><p class="hint">{{名前}}・{{推しマ}}を使った定期文にまとめて反映します。</p>';
 if(panel==='goals')html='<h2>今日の目標</h2><p class="hint">使わない項目は空欄で構いません。値を使う定期文を公開するときに確認します。</p><div class="form-grid">'+inputField('gift','ギフト名・絵文字',doc.settings.gift,{max:30})+inputField('goal','目標のギフト数',doc.settings.goal,{number:true,max:9})+inputField('current','現在のギフト数',doc.settings.current,{number:true,max:9})+inputField('peopleGoal','目標人数',doc.settings.peopleGoal,{number:true,max:9})+inputField('peopleCurrent','現在の人数',doc.settings.peopleCurrent,{number:true,max:9})+'</div><p class="hint">残り数・残り人数は自動計算します。「1K貢献」などの条件は定期文の本文で編集できます。</p>';
 if(panel==='messages'){
 const rows=doc.comments.filter(c=>!filter||c.category===filter);html='<h2>定期文</h2><div class="row"><label class="sr-only" for="categoryFilter">カテゴリで絞り込む</label><select id="categoryFilter" class="grow"><option value="">すべて</option>'+doc.categories.map(c=>`<option value="${esc(c.id)}" ${filter===c.id?'selected':''}>${esc(c.name)}</option>`).join('')+'</select><button class="btn primary" data-action="new">＋ 追加</button><button class="btn" data-action="undo" '+(!undo.length?'disabled':'')+'>元に戻す</button></div><div class="editor-list">'+rows.map(c=>{const t=resolveText(c.text,doc.settings);return `<article class="edit-row"><div class="row"><h3 class="grow">${esc(c.title)}</h3><span class="badge">${c.visible?'表示':'非表示'}</span>${c.pinned?'<span class="badge">固定</span>':''}</div><p class="summary">${esc(t.text)}</p><p class="hint ${t.missing.length||t.count>141?'warning':''}">${t.count}/141文字目安${t.missing.length?' ・ 未入力：'+esc(t.missing.join('・')):''}</p><div class="row"><button class="btn small" data-edit="${esc(c.id)}">編集</button><button class="btn small" data-duplicate="${esc(c.id)}">複製</button><button class="btn square" data-move="${esc(c.id)}" data-direction="-1" aria-label="${esc(c.title)}を上へ">↑</button><button class="btn square" data-move="${esc(c.id)}" data-direction="1" aria-label="${esc(c.title)}を下へ">↓</button><button class="btn small" data-toggle="${esc(c.id)}">${c.visible?'非表示にする':'表示する'}</button><button class="btn small danger" data-delete="${esc(c.id)}">削除</button></div></article>`;}).join('')+'</div>';
 }
 if(panel==='categories')html='<h2>カテゴリ</h2><div class="row"><input id="newCategory" class="grow" maxlength="40" placeholder="新しいカテゴリ名" aria-label="新しいカテゴリ名"><button class="btn" data-action="addCategory">追加</button></div><div class="editor-list">'+doc.categories.map(c=>`<div class="edit-row"><label for="cat_${esc(c.id)}">カテゴリ名</label><input id="cat_${esc(c.id)}" data-category-name="${esc(c.id)}" value="${esc(c.name)}" maxlength="40"><div class="row"><button class="btn small" data-category-toggle="${esc(c.id)}">${c.visible?'表示中：非表示にする':'非表示：表示する'}</button><button class="btn square" data-category-move="${esc(c.id)}" data-direction="-1" aria-label="${esc(c.name)}を上へ">↑</button><button class="btn square" data-category-move="${esc(c.id)}" data-direction="1" aria-label="${esc(c.name)}を下へ">↓</button></div></div>`).join('')+'</div>';
 if(panel==='sparkles')html='<h2>歌キラコメを作る</h2><p class="hint">基本情報の推しマを使います。追加した後も推しマの変更が反映されます。</p><div class="field"><label for="sparkleStyle">飾り</label><select id="sparkleStyle">'+SPARKLES.map((p,i)=>`<option value="${i}">${esc(p[0])}</option>`).join('')+'</select></div><div class="field"><label for="sparkleRepeat">繰り返し</label><select id="sparkleRepeat"><option value="1">1回</option><option value="2">2回</option><option value="3">3回</option></select></div><p id="sparkleLength" class="hint"></p><div id="sparklePreview" class="preview-text"></div><div class="row" style="margin-top:14px"><button class="btn primary" data-action="addSparkle">定期文に追加</button></div>';
 if(panel==='sharing'){
 const url=row?PUBLIC_URL+'?page='+encodeURIComponent(row.slug):'';
 html='<h2>共有・保存</h2><div class="panel"><h3>リスナー用URL</h3><p class="hint">'+(pub?.is_published?'公開中です。':'まだ公開されていません。公開後に共有してください。')+'</p>'+(url?'<input id="shareUrl" readonly aria-label="リスナー用URL" value="'+esc(url)+'"><div class="row" style="margin-top:10px"><button class="btn" data-action="copyUrl">URLをコピー</button><a class="btn" target="_blank" rel="noopener noreferrer" href="'+esc(url)+'">ページを開く</a></div>':'<p>最初に下書き保存すると、専用URLが作成されます。</p>')+'</div><div class="panel"><h3>バックアップ</h3><p class="hint">名前・目標・カテゴリ・非表示の文を含めて保存できます。</p><div class="row"><button class="btn" data-action="export">書き出す</button><button class="btn" data-action="import">読み込む</button></div></div><div class="panel"><h3>公開内容の管理</h3><div class="row"><button class="btn" data-action="restore" '+(!row?.last_published_draft?'disabled':'')+'>公開済みの内容へ戻す</button><button class="btn danger" data-action="unpublish" '+(!pub?.is_published?'disabled':'')+'>公開を停止</button></div><p class="hint">戻した内容は下書きです。確認してから公開してください。</p></div>'+(demo?'<button class="btn" data-action="login">ログインして公開する</button>':'');
 }
 $('panel').innerHTML=html;
 if(panel==='messages')$('categoryFilter').onchange=e=>{filter=e.target.value;renderPanel();};
 if(panel==='sparkles'){for(const id of ['sparkleStyle','sparkleRepeat'])$(id).onchange=showSparkle;showSparkle();}
}
function openPanel(p){if(recovery)return toast('先に一時保存した編集を確認してください。');panel=p;$('dashboard').hidden=true;$('panel').hidden=false;$('dashboardBtn').hidden=false;renderPanel();window.scrollTo({top:0});}
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>openPanel(b.dataset.panel));
$('panel').addEventListener('input',e=>{const k=e.target.dataset.setting;if(k)changed(()=>doc.settings[k]=e.target.value,false);});
$('panel').addEventListener('change',e=>{const id=e.target.dataset.categoryName;if(!id)return;if(e.target.value.trim())changed(()=>doc.categories.find(c=>c.id===id).name=e.target.value.trim(),false);else{e.target.value=doc.categories.find(c=>c.id===id).name;toast('カテゴリ名を入力してください。');}});
function sparkleText(){return Array(Number($('sparkleRepeat').value)).fill(SPARKLES[Number($('sparkleStyle').value)][1]).join(' ');}
function showSparkle(){const r=resolveText(sparkleText(),doc.settings);$('sparklePreview').textContent=r.text;$('sparkleLength').textContent=r.count+'/141文字目安'+(r.missing.length?' ・ 基本情報で推しマを入力してください':'');}
function editComment(id=null,initial=null){editId=id;const c=initial||doc.comments.find(c=>c.id===id)||{title:'',text:'',category:filter||doc.categories[0]?.id,visible:true,pinned:false};if(!c.category)return toast('先にカテゴリを追加してください。');$('editTitle').value=c.title;$('editText').value=c.text;$('editCategory').innerHTML=doc.categories.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');$('editCategory').value=c.category;$('editVisible').checked=c.visible;$('editPinned').checked=c.pinned;$('tokens').innerHTML=TOKENS.map(t=>`<button class="btn small" type="button" data-token="${esc(t)}">${esc(t)}</button>`).join('');editPreview();$('editDialog').showModal();}
function editPreview(){const r=resolveText($('editText').value,doc.settings);$('editPreview').textContent=r.text;$('editLength').textContent=r.count+'/141文字目安'+(r.missing.length?' ・ 未入力：'+r.missing.join('・'):'');}
$('editText').oninput=editPreview;$('tokens').onclick=e=>{const t=e.target.closest('[data-token]');if(!t)return;const el=$('editText');el.setRangeText('{{'+t.dataset.token+'}}',el.selectionStart,el.selectionEnd,'end');el.focus();editPreview();};
$('editForm').onsubmit=e=>{e.preventDefault();if(!editId&&doc.comments.length>=200)return toast('定期文は200件までです。');const next={id:editId||uid(),category:$('editCategory').value,title:$('editTitle').value.trim(),text:$('editText').value.trim(),visible:$('editVisible').checked,pinned:$('editPinned').checked};if(!next.title||!next.text)return;changed(()=>{if(editId)doc.comments[doc.comments.findIndex(c=>c.id===editId)]=next;else doc.comments.push(next);});$('editDialog').close();};
$('panel').onclick=async e=>{
 const b=e.target.closest('button');if(!b||busy)return;const a=b.dataset.action;
 if(b.dataset.edit)editComment(b.dataset.edit);
 if(b.dataset.toggle)changed(()=>{const c=doc.comments.find(c=>c.id===b.dataset.toggle);c.visible=!c.visible;});
 if(b.dataset.duplicate){if(doc.comments.length>=200)return toast('定期文は200件までです。');changed(()=>{const c=clone(doc.comments.find(c=>c.id===b.dataset.duplicate));c.id=uid();c.title=(c.title+' のコピー').slice(0,80);doc.comments.push(c);});}
 if(b.dataset.delete&&await ask('この定期文を削除しますか？','公開済みの文は、次に公開するまでは残ります。「元に戻す」で編集を取り消せます。','削除する'))changed(()=>doc.comments=doc.comments.filter(c=>c.id!==b.dataset.delete));
 if(b.dataset.move){const id=b.dataset.move,i=doc.comments.findIndex(c=>c.id===id),cat=doc.comments[i].category,indices=doc.comments.map((c,k)=>c.category===cat?k:-1).filter(k=>k>=0),pos=indices.indexOf(i),j=indices[pos+Number(b.dataset.direction)];if(j!==undefined)changed(()=>[doc.comments[i],doc.comments[j]]=[doc.comments[j],doc.comments[i]]);}
 if(b.dataset.categoryToggle)changed(()=>{const c=doc.categories.find(c=>c.id===b.dataset.categoryToggle);c.visible=!c.visible;});
 if(b.dataset.categoryMove){const i=doc.categories.findIndex(c=>c.id===b.dataset.categoryMove),j=i+Number(b.dataset.direction);if(j>=0&&j<doc.categories.length)changed(()=>[doc.categories[i],doc.categories[j]]=[doc.categories[j],doc.categories[i]]);}
 if(a==='new')editComment();if(a==='undo'&&undo.length){doc=undo.pop();dirty=true;remember();renderPanel();}
 if(a==='addCategory'){const name=$('newCategory').value.trim();if(!name)return;if(doc.categories.length>=20)return toast('カテゴリは20件までです。');changed(()=>doc.categories.push({id:uid('c'),name,visible:true}));}
 if(a==='addSparkle'){let cat=doc.categories.find(c=>c.id==='song');if(!cat){if(doc.categories.length>=20)return toast('歌用のカテゴリを用意してください。');changed(()=>doc.categories.push({id:'song',name:'🎤 歌キラコメ',visible:true}),false);}editComment(null,{title:'キラコメ｜'+SPARKLES[Number($('sparkleStyle').value)][0],text:sparkleText(),category:'song',visible:true,pinned:false});}
 if(a==='export')downloadJSON(normalizeDocument(doc),'teiki_backup_'+new Date().toISOString().slice(0,10)+'.json');if(a==='import')$('importFile').click();
 if(a==='copyUrl'){const ok=await copyText($('shareUrl').value);if(ok)toast('URLをコピーしました');else{$('shareUrl').focus();$('shareUrl').select();status('URLを長押ししてコピーしてください。');}}
 if(a==='restore'&&await ask('公開済みの内容に戻しますか？','現在の下書きはバックアップを書き出して残せます。公開ページは変わりません。','下書きに戻す')){if(await persist())await rpcAction('teiki_restore');}
 if(a==='unpublish'&&await ask('公開を停止しますか？','同じURLの閲覧を停止します。下書きは残り、あとで再公開できます。','公開を停止')){if(await persist())await rpcAction('teiki_unpublish');}
 if(a==='login')location.reload();
};
async function rpcAction(name){busy=true;$('studio').inert=true;try{const {data,error}=await db.rpc(name,{p_expected_revision:row.revision});if(error)throw error;applyRow(data);const p=await db.from('teiki_publications').select('*').eq('page_id',row.id).maybeSingle();if(p.error)throw p.error;pub=p.data;remember();renderPanel();status(name==='teiki_unpublish'?'公開を停止しました。':'公開済みの内容を下書きに戻しました。');}catch(e){status('反映できませんでした。再読み込み前にバックアップを書き出してください。'+friendly(e),true);}finally{busy=false;$('studio').inert=false;}}
$('importFile').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>300000)throw Error('ファイルが大きすぎます。');const d=normalizeDocument(JSON.parse(await f.text()));if(await ask('バックアップを読み込みますか？','現在の下書きを置き換えます。公開ページは変わりません。','読み込む'))changed(()=>doc=d);}catch(err){status(err.message,true);}};
function previewNow(){try{const d=publicDocument(doc),issues=publishIssues(doc);$('previewTitle').textContent=d.settings.name+'｜公開前の確認';$('issues').innerHTML=issues.length?'<div class="message"><b>公開前に確認してください</b><ul class="issues">'+issues.map(i=>'<li>'+esc(i)+'</li>').join('')+'</ul></div>':'<p class="message ok">'+d.comments.length+'件を公開できます。非表示の文は公開されません。</p>';$('previewCards').innerHTML=d.comments.map(c=>'<article class="comment-card"><div class="card-top"><h3>'+esc(c.title)+'</h3></div><p class="comment-body">'+esc(resolveText(c.text,d.settings).text)+'</p></article>').join('');$('confirmPublish').disabled=issues.length>0||demo;$('confirmPublish').textContent=demo?'公開にはログインが必要です':'この内容を公開';$('previewDialog').showModal();}catch(e){status(e.message,true);}}
$('previewBtn').onclick=previewNow;$('publishBtn').onclick=previewNow;
$('confirmPublish').onclick=async()=>{$('previewDialog').close();if(publishIssues(doc).length||demo)return;if(!await persist())return;busy=true;$('studio').inert=true;status('公開中…');try{const{data,error}=await db.rpc('teiki_publish',{p_expected_revision:row.revision});if(error)throw error;applyRow(data);const p=await db.from('teiki_publications').select('*').eq('page_id',row.id).maybeSingle();if(p.error)throw p.error;pub=p.data;remember();status('公開しました。同じ専用URLに最新の定期文が表示されます。');openPanel('sharing');}catch(e){status('公開できませんでした。下書きは保存されています。'+friendly(e),true);}finally{busy=false;$('studio').inert=false;}};
$('demoBtn').onclick=async()=>{try{demo=true;recovery=null;undo=[];doc=await starter();doc.settings.name='サンプル配信者';doc.settings.mark='🌟';const saved=storageGet(key(),null);if(saved?.document)doc=normalizeDocument(saved.document);row=null;pub=null;dirty=false;showStudio();status('お試し画面です。作った内容はバックアップで引き継げます。');}catch(e){status(e.message,true);}};
$('loginForm').onsubmit=async e=>{e.preventDefault();if(!db)return;const button=$('sendLogin');button.disabled=true;try{try{localStorage.setItem('teiki:return',String(Date.now()));}catch{}const{error}=await db.auth.signInWithOtp({email:$('email').value.trim(),options:{shouldCreateUser:true,emailRedirectTo:'https://tiktoklive-item-manager.vercel.app/home/admin/'}});if(error)throw error;status('ログイン用メールを送信しました。届いたリンクを同じブラウザで開いてください。');}catch(e){status('メールを送れませんでした。少し時間をおいてお試しください。',true);}finally{button.disabled=false;}};
$('logoutBtn').onclick=async()=>{if(demo){location.reload();return;}if(dirty&&!await ask('ログアウトしますか？','未保存の編集はこの端末に一時保存されています。必要なら先に下書き保存してください。','ログアウト'))return;await db.auth.signOut();location.reload();};
$('helpBtn').onclick=()=>$('helpDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
window.addEventListener('beforeunload',e=>{if(dirty&&!demo){e.preventDefault();e.returnValue='';}});
async function boot(){if(!db){status('ログイン機能を読み込めませんでした。再読み込みしてください。',true);return;}try{const {data}=await db.auth.getSession();if(!data.session){$('loginView').hidden=false;return;}const checked=await db.auth.getUser();if(checked.error)throw checked.error;user=checked.data.user;await loadAccount();}catch(e){status('ログイン状態を確認できませんでした。ログインし直すか、再読み込みしてください。',true);$('loginView').hidden=false;}}
if(db)db.auth.onAuthStateChange((_event,s)=>{if(user&&!demo&&s?.user?.id!==user.id){remember();dirty=false;setTimeout(()=>location.reload(),0);}});
if(location.hostname==='tashi-kusanose.github.io')location.replace('https://tiktoklive-item-manager.vercel.app/comments/admin/');else boot();
