import {API_URL,API_KEY,normalizeDocument,resolveText,copyText,storageGet,storageSet,esc} from './core.mjs?v=20260923.1';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),slug=params.get('page')||'natsumi',preview=params.get('preview')==='1';
let doc=null,active='normal',favorites=new Set(storageGet('teiki:favorites:'+slug,[])),stamp='',pending=null,toastTimer;const btnTimers=new WeakMap();
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2100);}
function message(t,error=false){$('pageMessage').className=t?'message'+(error?' error':''):'';$('pageMessage').textContent=t;}
async function fetchPublication(){if(!/^[a-zA-Z0-9_-]{1,80}$/.test(slug))throw Error('ページのURLを確認してください。');const r=await fetch(API_URL+'/rest/v1/teiki_publications?select=document,published_at,revision&slug=eq.'+encodeURIComponent(slug)+'&limit=1',{headers:{apikey:API_KEY},cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('読み込めませんでした。通信を確認して、もう一度お試しください。');const data=await r.json();if(!data.length){const e=Error('このページは未公開、または公開を終了しています。');e.notFound=true;throw e;}return data[0];}
function setDocument(data){doc=normalizeDocument(data.document);stamp=data.published_at||'';pending=null;$('updateNotice').hidden=true;if(!doc.categories.some(c=>c.id===active&&c.visible))active=doc.categories.find(c=>c.visible)?.id||'all';render();}
function render(){document.title=doc.settings.name+'｜'+doc.settings.title;$('pageTitle').textContent=[doc.settings.mark,doc.settings.name,doc.settings.title].filter(Boolean).join(' ');document.querySelector('.topbar').style.borderBottomColor=doc.settings.accent;const tabs=[...doc.categories.filter(c=>c.visible),{id:'favorites',name:'☆ お気に入り'},{id:'all',name:'すべて'}];$('categories').innerHTML=tabs.map(c=>`<button class="btn" data-category="${esc(c.id)}" aria-pressed="${active===c.id}">${esc(c.name)}</button>`).join('');renderCards();}
function renderCards(){const q=$('search').value.trim().toLocaleLowerCase(),cats=new Set(doc.categories.filter(c=>c.visible).map(c=>c.id));const rows=doc.comments.filter(c=>c.visible&&cats.has(c.category)).map(c=>({...c,resolved:resolveText(c.text,doc.settings)})).filter(c=>(active==='all'||(active==='favorites'?favorites.has(c.id):c.category===active))&&(!q||(c.title+' '+c.resolved.text).toLocaleLowerCase().includes(q))).sort((a,b)=>Number(b.pinned)-Number(a.pinned));$('resultCount').textContent=rows.length+'件'+(stamp?' ・ '+new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Tokyo'}).format(new Date(stamp))+' 更新':'');$('cards').innerHTML=rows.length?rows.map(c=>`<article class="comment-card"><div class="card-top"><h3>${c.pinned?'📌 ':''}${esc(c.title)}</h3><span class="length ${c.resolved.count>141?'warning':''}">${c.resolved.count}/141目安</span></div><p class="comment-body">${esc(c.resolved.text)}</p>${c.resolved.missing.length?'<p class="hint warning">配信者の入力待ちです</p>':''}<div class="card-bottom"><button class="btn square ${favorites.has(c.id)?'success':''}" data-favorite="${esc(c.id)}" aria-label="${esc(c.title)}をお気に入り${favorites.has(c.id)?'から外す':'に追加'}" aria-pressed="${favorites.has(c.id)}">${favorites.has(c.id)?'★':'☆'}</button><button class="btn primary" data-copy="${esc(c.id)}" aria-label="${esc(c.title)}をコピー" ${c.resolved.missing.length?'disabled':''}>コピー</button></div></article>`).join(''):'<p class="empty">'+(active==='favorites'?'☆を押した定期文がここに表示されます。':'該当する定期文がありません。')+'</p>';}
$('categories').onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;active=b.dataset.category;render();$('categories').querySelector(`[data-category="${CSS.escape(active)}"]`)?.scrollIntoView({block:'nearest',inline:'nearest'});window.scrollTo({top:0});};
$('search').oninput=()=>doc&&renderCards();
$('cards').onclick=async e=>{const f=e.target.closest('[data-favorite]');if(f){const id=f.dataset.favorite;if(favorites.has(id))favorites.delete(id);else favorites.add(id);if(!storageSet('teiki:favorites:'+slug,[...favorites]))toast('このブラウザではお気に入りを保存できません。');renderCards();return;}const b=e.target.closest('[data-copy]');if(!b||b.disabled)return;const row=doc.comments.find(c=>c.id===b.dataset.copy);if(!row)return;const r=resolveText(row.text,doc.settings);if(r.missing.length)return;b.disabled=true;const ok=await copyText(r.text);b.disabled=false;clearTimeout(btnTimers.get(b));if(ok){b.textContent='コピーしました ✓';b.classList.add('success');toast('コピーしました');btnTimers.set(b,setTimeout(()=>{b.textContent='コピー';b.classList.remove('success');},1600));}else{$('manualText').value=r.text;$('manualDialog').showModal();$('manualText').focus();$('manualText').select();}};
$('helpBtn').onclick=()=>$('helpDialog').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
async function checkUpdate(silent=false){if(preview)return;try{const p=await fetchPublication();if(!doc){setDocument(p);message('');return;}if(p.published_at!==stamp){pending=p;$('updateNotice').hidden=false;}else if(!silent)toast('最新の内容です');}catch(e){if(e.notFound){doc=null;$('cards').innerHTML='';$('categories').innerHTML='';$('resultCount').textContent='';message(e.message,true);}else if(!silent)message(e.message,true);}}
$('refreshBtn').onclick=()=>checkUpdate();$('applyUpdate').onclick=()=>{if(pending){setDocument(pending);message('');}};window.addEventListener('focus',()=>checkUpdate(true));document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkUpdate(true);});
async function boot(){if(preview){try{const p=JSON.parse(sessionStorage.getItem('teiki:preview'));if(!p?.document||Date.now()-p.at>3600000)throw Error();setDocument(p);message('プレビュー：まだ公開されていません');$('refreshBtn').hidden=true;}catch{message('編集画面からプレビューを開き直してください。',true);$('cards').innerHTML='';}return;}try{setDocument(await fetchPublication());}catch(e){message(e.message,true);$('cards').innerHTML='';}}boot();
