'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('ja-JP').format(n);
const iconPaths={boost:'M13 2 4 14h7l-1 8 10-13h-7l0-7Z',grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',gift:'M3 8h18v4H3z M5 12v9h14v-9 M12 8v13 M12 8H7a3 3 0 1 1 3-3l2 3z M12 8h5a3 3 0 1 0-3-3l-2 3z',calculator:'M5 2h14v20H5z M8 5h8v4H8z M8 13h1 M15 13h1 M8 17h1 M15 17h1',flag:'M4 22V3 M4 3c4-4 10 4 15 0v11c-5 4-11-4-15 0',medal:'M8 3 5 1 M16 3l3-2 M8 3l4 5 4-5 M12 8a6 6 0 1 0 0 12 6 6 0 0 0 0-12z M9 20l-1 3 4-2 4 2-1-3',info:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18z M12 7h.01 M12 11v6',close:'m6 6 12 12 M18 6 6 18',sparkle:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3z',page:'M5 2h9l5 5v15H5z M14 2v6h5 M8 12h8 M8 16h8',heart:'M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8z',like:'M7 10v11H3V10z M7 11l5-9c3 0 3 4 1 7h7c1 0 2 1 1 3l-2 8c0 1-1 1-2 1H7'};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${iconPaths[name]||iconPaths.sparkle}"/></svg>`;}
function hydrateIcons(root=document){$$('[data-icon]',root).forEach(e=>{e.innerHTML=icon(e.dataset.icon)});}
const gifts=[{id:'hand',name:'ハンドハート',short:'ハンドハート',price:100,box:'276 305 330 287',dailyPeople:100,weeklyPeople:500,dailyBonus:100000},{id:'gun',name:'マネーガン',short:'マネーガン',price:500,box:'949 299 331 296',dailyPeople:50,weeklyPeople:200,dailyBonus:150000},{id:'galaxy',name:'銀河',short:'銀河',price:1000,box:'584 845 383 346',dailyPeople:30,weeklyPeople:100,dailyBonus:200000}];
const missionData={daily:[{id:'visit',short:'ページ訪問',name:'イベントページを訪問',icon:'page',cost:0,bonus:500,condition:'TikTokアプリ内の<b>本イベントページを1回訪問</b>する。',note:'このガイドの閲覧では達成されません。TikTokアプリ内のイベントページを開いてください。'},{id:'heart',short:'新規ハートミー',name:'新規ハートミーを獲得',icon:'heart',cost:null,bonus:50000,condition:'1日に<b>新規ハートミーを100個</b>獲得する。',note:'過去にメンバーになっていない視聴者が対象。必要コインは、入力した単価 × 100個で計算します。'},...gifts.map(g=>({id:g.id,short:g.short,name:g.name,gift:g.id,cost:g.price*g.dailyPeople,bonus:g.dailyBonus,condition:`<b>${g.name}（${fmt(g.price)}コイン）を${fmt(g.dailyPeople)}人</b>から受け取る。`,note:'必要コインは、条件の人数全員が対象ギフトを1個ずつ送る場合の最小額です。人数条件に注意。'}))],weekly:[{id:'likes',short:'いいね',name:'500万いいねを獲得',icon:'like',cost:0,bonus:150000,condition:'イベント期間中に<b>いいねを5,000,000回</b>もらう。',note:'いいねへの通常pt加算は資料に記載なし。ここではミッションの報酬150,000ptを表示します。'},...gifts.map(g=>({id:g.id,short:g.short,name:g.name,gift:g.id,cost:g.price*g.weeklyPeople,bonus:300000,condition:`<b>${g.name}（${fmt(g.price)}コイン）を${fmt(g.weeklyPeople)}人</b>から受け取る。`,note:'視聴者の集計は毎日リセットされません。期間を通じて異なる視聴者から受け取る人数条件です。'}))]};
const pickerShort={visit:'訪問',heart:'新規',hand:'ハート',gun:'ガン',galaxy:'銀河',likes:'いいね'};
let selectedGift='hand',selectedMissions={daily:'visit',weekly:'likes'},missionGroup='daily',heartUnit=null,compareGroup='daily',comparePage=0;
const giftSvg=(g,extra='')=>`<svg viewBox="${g.box}" role="img" aria-label="${g.name}" ${extra}><image href="assets/gifts.png" width="1536" height="1451"/></svg>`;
function setView(view,changeHash=true){if(!['overview','gifts','points','missions','rewards'].includes(view))view='overview';$$('.view').forEach(e=>{e.hidden=e.id!==view});$$('[data-view]').forEach(e=>{if(e.dataset.view===view)e.setAttribute('aria-current','page');else e.removeAttribute('aria-current')});if(changeHash&&location.hash!==`#${view}`)history.pushState(null,'',`#${view}`);}
function selectTab(group,key){const list=$(`[data-tabgroup="${group}"]`);if(!list)return;const target=$(`[data-tab="${key}"]`,list);if(!target)return;$$('[role=tab]',list).forEach(b=>{const active=b===target;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;$('#'+b.getAttribute('aria-controls')).hidden=!active});if(group==='missions'){missionGroup=key;$('#mission-limit').textContent=key==='daily'?'各ミッション、1日最大1回':'各ミッション、期間中最大1回';}}
function renderGift(){const g=gifts.find(x=>x.id===selectedGift);$('#gift-picker').innerHTML=gifts.map(x=>`<button id="gift-tab-${x.id}" role="tab" data-gift="${x.id}" aria-controls="gift-detail" aria-selected="${x.id===g.id}" tabindex="${x.id===g.id?0:-1}">${x.name}<small>${fmt(x.price)} コイン</small></button>`).join('');$('#gift-detail').setAttribute('aria-labelledby',`gift-tab-${g.id}`);$('#gift-detail').innerHTML=`<article class="gift-card"><div class="gift-art">${giftSvg(g)}</div><div class="gift-content"><span class="eyebrow">MISSION GIFT · 0${gifts.indexOf(g)+1}</span><h2>${g.name}</h2><div class="gift-price">${fmt(g.price)}<small>コイン</small></div><div class="gift-mission-mini"><span>デイリー</span><b>${g.dailyPeople}人 / +${fmt(g.dailyBonus)}pt</b></div><div class="gift-mission-mini"><span>ウィークリー</span><b>${g.weeklyPeople}人 / +300,000pt</b></div><button class="primary-button" data-gift-mission="${g.id}">ミッションの内訳を見る</button></div></article>`;}
function costOf(m){return m.id==='heart'&&m.cost===null?(heartUnit===null?null:heartUnit*100):m.cost;}
function amounts(m){const cost=costOf(m);return {cost,base:cost,bonus:m.bonus,total:cost===null?null:cost+m.bonus};}
function missionBody(m,group){const a=amounts(m),gift=gifts.find(g=>g.id===m.gift),known=a.cost!==null;return `<article class="mission-card"><div class="mission-card-top"><div class="mission-icon">${gift?giftSvg(gift):`<span data-icon="${m.icon}"></span>`}</div><div><span class="eyebrow">${group==='daily'?'DAILY MISSION':'WEEKLY MISSION'} · 0${missionData[group].indexOf(m)+1}</span><h2>${m.name}</h2></div><button class="icon-button mission-help" data-mission-info="${group}:${m.id}" aria-label="達成条件の補足"><span data-icon="info"></span></button></div><p class="mission-condition">${m.condition}${m.id==='heart'?'<small>過去にメンバーになっていない視聴者が対象</small>':group==='weekly'&&m.gift?'<small>人数は期間累計。毎日リセットされません。</small>':''}</p><div class="mission-amounts"><div class="amount-cell"><span>必要コイン<br><em style="font-style:normal;font-size:12px">${m.id==='heart'?'入力単価から算出':'最小額'}</em></span><strong class="${known?'':'unknown'}">${known?fmt(a.cost):'未記載'}${known?'<small>コイン</small>':''}</strong><small>${gift?`${fmt(gift.price)} × ${fmt(a.cost/gift.price)}人`:m.id==='heart'?(known?`${fmt(heartUnit)} × 100個`:'単価の記載なし'):'ギフト送付なし'}</small></div><div class="amount-cell"><span>イベントpt<br><em style="font-style:normal;font-size:12px">${gift||m.id==='heart'?'参考値':'この行動での加算'}</em></span><strong class="${known?'':'unknown'}">${known?fmt(a.base):'未確定'}${known?'<small>pt</small>':''}</strong><small>${gift||m.id==='heart'?'1コイン＝1ダイヤ仮定':m.id==='likes'?'いいねptの記載なし':'通常ptの加算なし'}</small></div><div class="amount-cell bonus"><span>ボーナスpt<br><em style="font-style:normal;font-size:12px">達成報酬</em></span><strong>${fmt(a.bonus)}<small>pt</small></strong><small>${group==='daily'?'1日最大1回':'期間中最大1回'}</small></div></div><div class="mission-total"><div><span>合計ポイント${a.cost>0?'（参考）':''}</span><small>通常イベントpt ＋ ボーナスpt</small></div><strong class="${known?'':'unknown-total'}">${known?fmt(a.total):'50,000 + 通常pt'}${known?'<small>pt</small>':''}</strong></div>${m.id==='heart'?`<label class="heart-price">ハートミー1個の単価（コイン）<input id="heart-unit" type="number" min="1" max="1000000" step="1" inputmode="numeric" placeholder="未入力" value="${heartUnit===null?'':heartUnit}" aria-label="ハートミー1個のコイン単価"></label>`:''}</article>`;}
function renderMissions(group){const list=missionData[group],sel=selectedMissions[group];$(`#${group}-picker`).innerHTML=list.map(m=>`<button id="mission-tab-${group}-${m.id}" role="tab" aria-controls="${group}-detail" data-mission="${m.id}" data-group="${group}" aria-label="${m.short}" aria-selected="${m.id===sel}" tabindex="${m.id===sel?0:-1}"><span class="picker-long">${m.short}</span><span class="picker-short">${pickerShort[m.id]}</span></button>`).join('');const m=list.find(x=>x.id===sel);const detail=$(`#${group}-detail`);detail.setAttribute('aria-labelledby',`mission-tab-${group}-${m.id}`);detail.innerHTML=missionBody(m,group);hydrateIcons(detail);}
function renderCalcInputs(){ $('#calc-daily-fields').innerHTML=missionData.daily.map(m=>`<label class="calc-row"><span>${m.short}<small>+${fmt(m.bonus)}pt / 日</small></span><select data-calc-daily="${m.id}" aria-label="${m.short}の達成日数">${Array.from({length:6},(_,i)=>`<option value="${i}">${i}日</option>`).join('')}</select></label>`).join('');$('#calc-weekly-fields').innerHTML=missionData.weekly.map(m=>`<label class="calc-row"><span>${m.short}<small>+${fmt(m.bonus)}pt${m.id==='likes'?' / 500万回':` / ${gifts.find(g=>g.id===m.gift).weeklyPeople}人`}</small></span><input type="checkbox" data-calc-weekly="${m.id}" aria-label="${m.short}のウィークリーミッション達成"></label>`).join('');}
function calculate(diamonds,daily,weekly){return {base:diamonds,daily:missionData.daily.reduce((s,m)=>s+m.bonus*(daily[m.id]||0),0),weekly:missionData.weekly.reduce((s,m)=>s+(weekly[m.id]?m.bonus:0),0)};}
function updateCalc(){const field=$('#diamonds'),raw=field.value,n=Number(raw);const valid=raw!==''&&Number.isFinite(n)&&Number.isInteger(n)&&n>=0&&n<=1000000000;field.setAttribute('aria-invalid',String(!valid));$('#calc-error').textContent=valid?'':'ダイヤ数は0〜1,000,000,000の整数で入力してください。';const d=Object.fromEntries($$('[data-calc-daily]').map(e=>[e.dataset.calcDaily,Number(e.value)])),w=Object.fromEntries($$('[data-calc-weekly]').map(e=>[e.dataset.calcWeekly,e.checked]));const r=calculate(valid?n:0,d,w);$('#result-base').textContent=valid?`${fmt(r.base)} pt`:'—';$('#result-daily').textContent=`${fmt(r.daily)} pt`;$('#result-weekly').textContent=`${fmt(r.weekly)} pt`;$('#result-total').textContent=valid?fmt(r.base+r.daily+r.weekly):'—';$('#result-total').dataset.long=String(r.base+r.daily+r.weekly>99999999);return {...r,total:valid?r.base+r.daily+r.weekly:null};}
const dialog=$('#detail-dialog');
function showDialog(title,html){$('#dialog-title').textContent=title;$('#dialog-content').innerHTML=html;if(!dialog.open)dialog.showModal();hydrateIcons(dialog);}
const sources={event:{name:'紹介・特典',path:'assets/event.png'},rules:{name:'イベント概要',path:'assets/rules.png'},gifts:{name:'対象ギフト',path:'assets/gifts.png'},missions:{name:'ミッション',path:'assets/missions.png'}};
function showSource(key){const s=sources[key]||sources.event;showDialog('イベントの提供資料',`<div class="source-tabs" role="group" aria-label="原本を切り替える">${Object.entries(sources).map(([k,x])=>`<button data-source="${k}" aria-pressed="${k===key}">${x.name}</button>`).join('')}</div><p class="source-caption">提供されたスクリーンショットです。最新の内容はTikTokアプリ内の公式案内をご確認ください。</p><img class="source-image" src="${s.path}" alt="COMMUNITY BOOST ${s.name}の原本">`);dialog.scrollTop=0;}
function showInfo(kind){if(kind==='assumption'){showDialog('ミッションの計算前提',`<p><b>公式ルールは「1ダイヤモンド＝1ポイント」です。</b>必要コインは「ギフト単価 × 条件人数 × 1個」で求めた最小額です。</p><p>このガイドのミッション内訳では、<b>1コイン＝1ダイヤと仮定</b>して通常イベントptと合計ptを表示しています。コインと受取ダイヤの換算は提供資料に記載されていないため、確定値ではありません。</p><p>新規ハートミーの単価も資料に記載がありません。単価を入力すると必要コイン・通常pt・合計ptの参考値を表示します。未入力のとき、50,000ptはミッション報酬だけの値です。</p><p>通常ptは上限の範囲内で計算。同じギフトがデイリー・ウィークリーの両方の条件に使われる場合、比較表の通常ptをそのまま足すと二重計上になります。期間合計の試算は「ポイント計算」をご利用ください。</p>`);}else showDialog('このガイドについて',`<p>COMMUNITY BOOSTの案内画像4枚をもとに、KazzCompanyが作成した非公式のイベントガイドです。TikTokの公式サイトではありません。</p><p>開催期間は2026年10月13日（火）12:00〜10月17日（土）23:59、日本時間として表示しています。</p><p>ここでの閲覧・試算・チェック操作は、TikTokのミッション達成やランキングには反映されません。試算結果はこの画面内だけのものです。</p><p>ギフト単価・集計条件・特典などは、TikTokアプリ内の最新の公式案内を優先してください。</p><p>情報整理日：2026年10月9日</p>`);}
function compareValue(n,unit){return n===null?'未確定':`${fmt(n)}<small>${unit}</small>`;}
function showComparison(){const list=missionData[compareGroup],pages=Math.ceil(list.length/2);comparePage=Math.min(comparePage,pages-1);const rows=list.map(m=>{const a=amounts(m);return `<tr><th scope="row">${m.short}</th><td>${a.cost===null?'未記載':fmt(a.cost)}</td><td>${a.base===null?'未確定':fmt(a.base)}</td><td>${fmt(a.bonus)}</td><td>${a.total===null?'50,000 + 通常pt':fmt(a.total)}</td></tr>`}).join('');const cards=list.slice(comparePage*2,comparePage*2+2).map(m=>{const a=amounts(m);return `<article class="compare-card"><h3>${m.short}</h3><dl><div><dt>必要コイン</dt><dd>${a.cost===null?'未記載':compareValue(a.cost,'コイン')}</dd></div><div><dt>通常イベントpt（参考）</dt><dd>${compareValue(a.base,'pt')}</dd></div><div><dt>ボーナスpt</dt><dd>${compareValue(a.bonus,'pt')}</dd></div><div><dt>合計pt${a.total!==null&&a.cost>0?'（参考）':''}</dt><dd>${a.total===null?'<span style="font-size:16px">50,000 + 通常pt</span>':compareValue(a.total,'pt')}</dd></div></dl></article>`}).join('');showDialog('ミッションを一覧で比較',`<div class="compare-switch" role="group" aria-label="比較するミッション"><button data-compare-group="daily" aria-pressed="${compareGroup==='daily'}">デイリー</button><button data-compare-group="weekly" aria-pressed="${compareGroup==='weekly'}">ウィークリー</button></div><p class="compare-note">各ミッション1回達成時。1コイン＝1ダイヤと仮定した参考計算です。</p><table class="compare-table"><thead><tr><th scope="col">ミッション</th><th scope="col">必要コイン</th><th scope="col">通常pt（参考）</th><th scope="col">ボーナスpt</th><th scope="col">合計pt（参考）</th></tr></thead><tbody>${rows}</tbody></table><div class="compare-mobile">${cards}<div class="pagination"><button data-compare-page="${comparePage-1}" ${comparePage===0?'disabled':''}>前へ</button><span>${comparePage+1} / ${pages}</span><button data-compare-page="${comparePage+1}" ${comparePage===pages-1?'disabled':''}>次へ</button></div></div><p class="compare-note">${compareGroup==='daily'?'各1日最大1回。5種の報酬合計は500,500pt / 日。':'各期間中最大1回。4種の報酬合計は1,050,000pt。'} ギフトが両方の条件に使われる場合、通常ptは重複して足さないでください。</p>`);}
function updateCountdown(){const now=Date.now(),start=Date.parse('2026-10-13T12:00:00+09:00'),end=Date.parse('2026-10-18T00:00:00+09:00');const started=now>=start,finished=now>=end;$('#event-state').textContent=finished?'終了':started?'開催中':'開催前';$('#countdown-label').textContent=finished?'開催期間':'開幕まで';if(started&&!finished)$('#countdown-label').textContent='終了まで';if(finished){$('#countdown').textContent='終了しました';return;}const hours=Math.max(0,Math.ceil(((started?end:start)-now)/3600000)),days=Math.floor(hours/24);$('#countdown').textContent=`${days}日 ${hours%24}時間`;}
function focusPicker(id){const e=document.getElementById(id);if(e)e.focus({preventScroll:true});}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){setView(b.dataset.view);}if(b.dataset.go){setView(b.dataset.go);if(b.dataset.missionGroup)selectTab('missions',b.dataset.missionGroup);}if(b.dataset.tab){const group=b.closest('[data-tabgroup]').dataset.tabgroup;selectTab(group,b.dataset.tab);}if(b.hasAttribute('data-open-calculator')){setView('points');selectTab('points','calc');}if(b.dataset.gift){selectedGift=b.dataset.gift;renderGift();focusPicker(`gift-tab-${selectedGift}`);}if(b.dataset.giftMission){selectedMissions.daily=b.dataset.giftMission;renderMissions('daily');selectTab('missions','daily');setView('missions');}if(b.dataset.mission){selectedMissions[b.dataset.group]=b.dataset.mission;renderMissions(b.dataset.group);focusPicker(`mission-tab-${b.dataset.group}-${b.dataset.mission}`);}if(b.dataset.missionInfo){const [group,id]=b.dataset.missionInfo.split(':');const m=missionData[group].find(x=>x.id===id);showDialog(m.name+'：達成条件',`<p>${m.condition}</p><p>${m.note}</p><p>${group==='daily'?'各ミッション1日最大1回。':'各ミッション期間中最大1回。'}達成報酬は${fmt(m.bonus)}ptです。</p>`);}if(b.dataset.source)showSource(b.dataset.source);if(b.dataset.info)showInfo(b.dataset.info);if(b.id==='close-dialog')dialog.close();if(b.id==='mission-compare'){compareGroup=missionGroup;comparePage=0;showComparison();}if(b.dataset.compareGroup){compareGroup=b.dataset.compareGroup;comparePage=0;showComparison();}if(b.dataset.comparePage!==undefined){comparePage=Number(b.dataset.comparePage);showComparison();dialog.scrollTop=0;}if(b.id==='calc-clear'){ $('#diamonds').value='0';$$('[data-calc-daily]').forEach(x=>x.value='0');$$('[data-calc-weekly]').forEach(x=>x.checked=false);updateCalc();}if(b.id==='calc-example'){$('#diamonds').value='10000';$$('[data-calc-daily]').forEach(x=>x.value=x.dataset.calcDaily==='hand'?'1':'0');$$('[data-calc-weekly]').forEach(x=>x.checked=false);selectTab('calc','base');updateCalc();}});
document.addEventListener('input',e=>{if(e.target.id==='diamonds')updateCalc();});
document.addEventListener('change',e=>{if(e.target.matches('[data-calc-daily],[data-calc-weekly]'))updateCalc();if(e.target.id==='heart-unit'){const value=e.target.value,n=Number(value);if(value===''||(Number.isInteger(n)&&n>=1&&n<=1000000)){heartUnit=value===''?null:n;renderMissions('daily');$('#heart-unit').focus({preventScroll:true});}else{e.target.setCustomValidity('1〜1,000,000の整数を入力してください。');e.target.reportValidity();}}});
document.addEventListener('input',e=>{if(e.target.id==='heart-unit')e.target.setCustomValidity('');});
document.addEventListener('keydown',e=>{const b=e.target.closest('[role=tab]');if(!b||!['ArrowRight','ArrowLeft','ArrowDown','ArrowUp','Home','End'].includes(e.key))return;const buttons=$$('[role=tab]',b.closest('[role=tablist]'));let i=buttons.indexOf(b);i=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'||e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;e.preventDefault();buttons[i].click();const fresh=document.getElementById(buttons[i].id);if(fresh)fresh.focus({preventScroll:true});});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
window.addEventListener('popstate',()=>setView(location.hash.slice(1),false));window.addEventListener('hashchange',()=>setView(location.hash.slice(1),false));
hydrateIcons();renderGift();renderMissions('daily');renderMissions('weekly');renderCalcInputs();updateCalc();updateCountdown();setInterval(updateCountdown,60000);setView(location.hash.slice(1),false);
// Optional browser agent interface uses the same calculator state as the UI.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'calculate_community_boost_points',title:'COMMUNITY BOOSTのポイントを試算',description:'対象ダイヤ数と達成回数を試算フォームに設定し、期間合計ポイントと内訳を表示する。TikTokへは送信しない。',inputSchema:{type:'object',additionalProperties:false,required:['diamonds'],properties:{diamonds:{type:'integer',minimum:0,maximum:1000000000},daily:{type:'object',additionalProperties:false,properties:Object.fromEntries(missionData.daily.map(m=>[m.id,{type:'integer',minimum:0,maximum:5}]))},weekly:{type:'object',additionalProperties:false,properties:Object.fromEntries(missionData.weekly.map(m=>[m.id,{type:'boolean'}]))}}},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['diamonds','daily','weekly'].includes(k)))throw new Error('Invalid input');const {diamonds,daily={},weekly={}}=input;if(!Number.isInteger(diamonds)||diamonds<0||diamonds>1000000000)throw new Error('Invalid diamonds');if(!daily||typeof daily!=='object'||Array.isArray(daily)||Object.entries(daily).some(([k,v])=>!missionData.daily.some(m=>m.id===k)||!Number.isInteger(v)||v<0||v>5))throw new Error('Invalid daily counts');if(!weekly||typeof weekly!=='object'||Array.isArray(weekly)||Object.entries(weekly).some(([k,v])=>!missionData.weekly.some(m=>m.id===k)||typeof v!=='boolean'))throw new Error('Invalid weekly flags');$('#diamonds').value=String(diamonds);$$('[data-calc-daily]').forEach(e=>e.value=String(daily[e.dataset.calcDaily]||0));$$('[data-calc-weekly]').forEach(e=>e.checked=Boolean(weekly[e.dataset.calcWeekly]));setView('points');selectTab('points','calc');return updateCalc();}},{signal:lifecycle.signal})).catch(()=>{});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}catch{}}
